import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { type JsonValue, readJsonFile, writeJsonFile } from "./lib/json";
import { assertPathExists, upstreamRoot, workspaceRoot } from "./lib/paths";

type ElegantTheme = {
    colors: Record<string, string>;
};

const upstreamThemePath = resolve(
    upstreamRoot,
    "elegant-theme",
    "resources",
    "theme",
    "elegant-dark.theme.json",
);
const upstreamSchemePath = resolve(
    upstreamRoot,
    "elegant-theme",
    "resources",
    "theme",
    "elegant-dark.theme.xml",
);
const targetThemePath = resolve(workspaceRoot, "themes", "mk-theme-dark-color-theme.json");

assertPathExists(upstreamThemePath, "ElegantTheme JSON");
assertPathExists(upstreamSchemePath, "ElegantTheme editor scheme");

const upstreamTheme = readJsonFile(upstreamThemePath) as ElegantTheme;
const upstreamScheme = readFileSync(upstreamSchemePath, "utf8");

if (!upstreamTheme.colors || upstreamScheme.length < 100) {
    throw new Error("ElegantTheme upstream files are not usable.");
}

const color = (name: string): string => {
    const value = upstreamTheme.colors[name];

    if (!value) {
        throw new Error(`Missing ElegantTheme color: ${name}`);
    }

    return value;
};

const theme: JsonValue = {
    name: "mK Theme Dark",
    type: "dark",
    semanticHighlighting: true,
    colors: {
        "activityBar.background": color("dark"),
        "activityBar.border": color("gray"),
        "activityBar.foreground": color("white"),
        "activityBar.inactiveForeground": color("gray5"),
        "activityBarBadge.background": color("primarySecondary"),
        "activityBarBadge.foreground": color("pureWhite"),
        "badge.background": color("primaryTertiary"),
        "badge.foreground": color("pureWhite"),
        "breadcrumb.activeSelectionForeground": color("pureWhite"),
        "breadcrumb.background": color("editor"),
        "breadcrumb.focusForeground": color("white"),
        "breadcrumb.foreground": color("white2"),
        "button.background": color("primary"),
        "button.foreground": color("pureWhite"),
        "button.hoverBackground": color("primarySecondary"),
        "checkbox.background": color("gray2"),
        "checkbox.border": color("gray3"),
        "commandCenter.background": color("dark"),
        "commandCenter.border": color("gray3"),
        "commandCenter.foreground": color("white"),
        "debugToolBar.background": color("gray2"),
        "dropdown.background": color("dark"),
        "dropdown.border": color("gray"),
        "dropdown.foreground": color("white"),
        "editor.background": color("editor"),
        "editor.findMatchBackground": "#2b2f36",
        "editor.findMatchBorder": "#e0992d",
        "editor.findMatchHighlightBackground": "#2b2f36aa",
        "editor.foreground": "#a7b4c2",
        "editor.lineHighlightBackground": "#24272b",
        "editor.selectionBackground": "#152e4f",
        "editor.wordHighlightBackground": "#40332b",
        "editor.wordHighlightStrongBackground": "#40332b",
        "editorBracketMatch.background": color("gray4"),
        "editorBracketMatch.border": "#ffef28",
        "editorCursor.foreground": "#2075eb",
        "editorGutter.background": color("editor"),
        "editorIndentGuide.activeBackground1": "#2075eb",
        "editorIndentGuide.background1": "#373b42",
        "editorLineNumber.activeForeground": "#a7b4c2",
        "editorLineNumber.foreground": color("gray4"),
        "editorOverviewRuler.border": color("editor"),
        "editorRuler.foreground": "#373b42",
        "editorSuggestWidget.background": color("editor"),
        "editorSuggestWidget.border": color("gray"),
        "editorSuggestWidget.foreground": color("white2"),
        "editorSuggestWidget.highlightForeground": color("primarySecondary"),
        "editorSuggestWidget.selectedBackground": color("gray2"),
        "editorWidget.background": color("editor"),
        "editorWidget.border": color("gray"),
        focusBorder: color("primarySecondary"),
        foreground: color("treeText"),
        "input.background": color("dark"),
        "input.border": color("gray"),
        "input.foreground": color("white"),
        "input.placeholderForeground": color("gray5"),
        "list.activeSelectionBackground": color("primaryTertiary"),
        "list.activeSelectionForeground": color("pureWhite"),
        "list.focusBackground": color("primaryTertiary"),
        "list.hoverBackground": color("gray"),
        "list.inactiveSelectionBackground": color("gray"),
        "list.inactiveSelectionForeground": color("white"),
        "menu.background": color("dark"),
        "menu.foreground": color("white"),
        "menu.selectionBackground": color("primaryTertiary"),
        "notificationCenter.border": color("gray"),
        "notifications.background": color("gray2"),
        "notifications.border": color("gray"),
        "panel.background": color("dark"),
        "panel.border": color("gray"),
        "panelTitle.activeBorder": color("primarySecondary"),
        "panelTitle.activeForeground": color("white"),
        "panelTitle.inactiveForeground": color("gray5"),
        "peekView.border": color("primarySecondary"),
        "peekViewEditor.background": color("editor"),
        "peekViewResult.background": color("dark"),
        "progressBar.background": color("primarySecondary"),
        "scrollbarSlider.activeBackground": color("scrollHoverThumb"),
        "scrollbarSlider.background": color("scrollThumb"),
        "scrollbarSlider.hoverBackground": color("scrollHoverThumb"),
        "sideBar.background": color("dark"),
        "sideBar.border": color("gray"),
        "sideBar.foreground": color("treeText"),
        "sideBarSectionHeader.background": color("dark"),
        "sideBarSectionHeader.border": color("gray"),
        "sideBarTitle.foreground": color("white"),
        "statusBar.background": color("primaryTertiary"),
        "statusBar.foreground": color("pureWhite"),
        "statusBar.noFolderBackground": color("gray2"),
        "tab.activeBackground": color("editor"),
        "tab.activeBorderTop": color("primarySecondary"),
        "tab.activeForeground": color("white"),
        "tab.border": color("gray"),
        "tab.hoverBackground": color("gray"),
        "tab.inactiveBackground": color("editor"),
        "tab.inactiveForeground": color("gray5"),
        "terminal.background": color("editor"),
        "terminal.foreground": "#a7b4c2",
        "terminal.ansiBlue": "#4997fa",
        "terminal.ansiBrightBlue": "#2075eb",
        "terminal.ansiBrightCyan": "#13abc0",
        "terminal.ansiBrightGreen": "#009460",
        "terminal.ansiBrightMagenta": "#d674b9",
        "terminal.ansiBrightRed": "#e80854",
        "terminal.ansiBrightWhite": "#ffffff",
        "terminal.ansiBrightYellow": "#e0992d",
        "terminal.ansiCyan": "#12b8a2",
        "terminal.ansiGreen": "#009460",
        "terminal.ansiMagenta": "#8686d1",
        "terminal.ansiRed": "#db7672",
        "terminal.ansiWhite": "#d0d1da",
        "terminal.ansiYellow": "#eb8800",
        "titleBar.activeBackground": color("dark"),
        "titleBar.activeForeground": color("white"),
        "titleBar.border": color("gray"),
        "titleBar.inactiveBackground": color("dark"),
        "titleBar.inactiveForeground": color("gray5"),
    },
    tokenColors: [
        {
            scope: ["comment", "punctuation.definition.comment"],
            settings: { foreground: "#5b697c", fontStyle: "italic" },
        },
        {
            scope: ["string", "constant.other.symbol"],
            settings: { foreground: "#009963" },
        },
        {
            scope: ["constant.numeric", "constant.language", "support.constant"],
            settings: { foreground: "#eb8800" },
        },
        {
            scope: ["keyword", "storage", "storage.type"],
            settings: { foreground: "#e0992d" },
        },
        {
            scope: ["entity.name.function", "support.function", "meta.function-call"],
            settings: { foreground: "#4997fa" },
        },
        {
            scope: ["entity.name.type", "entity.name.class", "support.type", "support.class"],
            settings: { foreground: "#12b8a2" },
        },
        {
            scope: ["variable", "variable.other.readwrite"],
            settings: { foreground: "#8686d1" },
        },
        {
            scope: ["variable.parameter", "meta.function.parameters"],
            settings: { foreground: "#13abc0" },
        },
        {
            scope: ["variable.other.property", "support.variable.property"],
            settings: { foreground: "#a7b4c2" },
        },
        {
            scope: ["entity.other.attribute-name", "meta.decorator"],
            settings: { foreground: "#e0992d" },
        },
        {
            scope: ["entity.name.tag", "support.type.property-name"],
            settings: { foreground: "#4997fa" },
        },
        {
            scope: ["invalid", "invalid.illegal"],
            settings: { foreground: "#bc3f3c", fontStyle: "underline" },
        },
    ],
    semanticTokenColors: {
        class: "#12b8a2",
        enum: "#12b8a2",
        function: "#4997fa",
        interface: "#12b8a2",
        keyword: "#e0992d",
        method: "#4997fa",
        namespace: "#e0992d",
        parameter: "#13abc0",
        property: "#a7b4c2",
        string: "#009963",
        type: "#12b8a2",
        typeParameter: "#e0992d",
        variable: "#8686d1",
    },
};

const neutralWorkbenchColors: Record<string, string> = {
    "activityBar.activeBackground": "#171717",
    "activityBar.activeBorder": "#a1fb1a",
    "activityBar.activeFocusBorder": "#a1fb1a",
    "activityBar.background": "#111111",
    "activityBar.border": "#242424",
    "activityBar.foreground": "#a1fb1a",
    "activityBar.inactiveForeground": "#717171",
    "activityBarBadge.background": "#a1fb1a",
    "activityBarBadge.foreground": "#111111",
    "auxiliaryBar.background": "#111111",
    "auxiliaryBar.border": "#242424",
    "auxiliaryBar.foreground": "#cfcfcf",
    "auxiliaryBarTitle.foreground": "#d8d8d8",
    "badge.background": "#2a2a2a",
    "badge.foreground": "#d8d8d8",
    "breadcrumb.activeSelectionForeground": "#f4f4f4",
    "breadcrumb.background": "#171717",
    "breadcrumb.focusForeground": "#e7e7e7",
    "breadcrumb.foreground": "#858585",
    "charts.green": "#a1fb1a",
    "charts.lines": "#a1fb1a",
    "button.background": "#252525",
    "button.border": "#363636",
    "button.foreground": "#f0f0f0",
    "button.hoverBackground": "#303030",
    "button.secondaryBackground": "#1f1f1f",
    "button.secondaryForeground": "#d8d8d8",
    "button.secondaryHoverBackground": "#292929",
    "checkbox.background": "#181818",
    "checkbox.border": "#3a3a3a",
    "checkbox.selectBackground": "#202020",
    "checkbox.selectBorder": "#a1fb1a",
    "commandCenter.activeBackground": "#242424",
    "commandCenter.activeBorder": "#a1fb1a",
    "commandCenter.background": "#171717",
    "commandCenter.border": "#2b2b2b",
    "commandCenter.foreground": "#d8d8d8",
    "commandCenter.inactiveBorder": "#242424",
    "debugToolBar.background": "#1b1b1b",
    descriptionForeground: "#858585",
    "dropdown.background": "#181818",
    "dropdown.border": "#333333",
    "dropdown.foreground": "#d8d8d8",
    "editor.background": "#171717",
    "editor.findMatchBackground": "#3b321f",
    "editor.findMatchBorder": "#e0992d",
    "editor.findMatchHighlightBackground": "#2b2519",
    "editor.foreground": "#cfcfcf",
    "editor.lineHighlightBackground": "#202020",
    "editor.lineHighlightBorder": "#242424",
    "editor.rangeHighlightBackground": "#a1fb1a12",
    "editor.snippetFinalTabstopHighlightBorder": "#a1fb1a",
    "editor.snippetTabstopHighlightBackground": "#a1fb1a1a",
    "editor.selectionBackground": "#273244",
    "editor.wordHighlightBackground": "#242424",
    "editor.wordHighlightStrongBackground": "#2b2b2b",
    "editorBracketMatch.background": "#242424",
    "editorBracketMatch.border": "#858585",
    "editorCursor.foreground": "#d8d8d8",
    "editorGroup.border": "#242424",
    "editorGroup.dropBackground": "#24242480",
    "editorGroupHeader.border": "#242424",
    "editorGroupHeader.noTabsBackground": "#151515",
    "editorGroupHeader.tabsBackground": "#151515",
    "editorGroupHeader.tabsBorder": "#242424",
    "editorGutter.background": "#171717",
    "editorIndentGuide.activeBackground1": "#4a4a4a",
    "editorIndentGuide.background1": "#242424",
    "editorLineNumber.activeForeground": "#a8a8a8",
    "editorLineNumber.foreground": "#555555",
    "editorOverviewRuler.border": "#171717",
    "editorRuler.foreground": "#242424",
    "editorSuggestWidget.background": "#181818",
    "editorSuggestWidget.border": "#2b2b2b",
    "editorSuggestWidget.foreground": "#d8d8d8",
    "editorSuggestWidget.highlightForeground": "#a1fb1a",
    "editorSuggestWidget.selectedBackground": "#262626",
    "editorUnnecessaryCode.border": "#a1fb1a66",
    "editorWidget.background": "#181818",
    "editorWidget.border": "#2b2b2b",
    "extensionButton.prominentBackground": "#252525",
    "extensionButton.prominentForeground": "#a1fb1a",
    "extensionButton.prominentHoverBackground": "#303030",
    focusBorder: "#a1fb1a",
    foreground: "#d8d8d8",
    "input.background": "#181818",
    "input.border": "#333333",
    "inputOption.activeForeground": "#a1fb1a",
    "input.foreground": "#d8d8d8",
    "input.placeholderForeground": "#707070",
    "inputOption.activeBackground": "#252525",
    "inputOption.activeBorder": "#a1fb1a",
    "keybindingLabel.background": "#222222",
    "keybindingLabel.border": "#333333",
    "keybindingLabel.bottomBorder": "#242424",
    "keybindingLabel.foreground": "#d8d8d8",
    "link.activeForeground": "#a1fb1a",
    "textLink.activeForeground": "#a1fb1a",
    "textLink.foreground": "#a1fb1a",
    "list.activeSelectionBackground": "#252525",
    "list.activeSelectionForeground": "#f2f2f2",
    "list.activeSelectionIconForeground": "#a1fb1a",
    "list.focusBackground": "#242424",
    "list.focusForeground": "#f2f2f2",
    "list.focusHighlightForeground": "#a1fb1a",
    "list.focusOutline": "#a1fb1a",
    "list.highlightForeground": "#a1fb1a",
    "list.hoverBackground": "#202020",
    "list.hoverForeground": "#eeeeee",
    "list.inactiveSelectionBackground": "#202020",
    "list.inactiveSelectionForeground": "#d8d8d8",
    "menu.background": "#171717",
    "menu.border": "#303030",
    "menu.foreground": "#d8d8d8",
    "menu.selectionBorder": "#303030",
    "menu.selectionBackground": "#242424",
    "menu.selectionForeground": "#f2f2f2",
    "menu.separatorBackground": "#303030",
    "menubar.selectionBackground": "#242424",
    "menubar.selectionBorder": "#303030",
    "menubar.selectionForeground": "#f2f2f2",
    "notificationCenter.border": "#2b2b2b",
    "notificationLink.foreground": "#a1fb1a",
    "notifications.background": "#181818",
    "notifications.border": "#2b2b2b",
    "notifications.foreground": "#d8d8d8",
    "panel.background": "#111111",
    "panel.border": "#282828",
    "panelTitle.activeBorder": "#a1fb1a",
    "panelTitle.activeForeground": "#e8e8e8",
    "panelTitle.inactiveForeground": "#767676",
    "peekView.border": "#a1fb1a",
    "peekViewEditor.background": "#171717",
    "peekViewResult.background": "#181818",
    "pickerGroup.border": "#2b2b2b",
    "pickerGroup.foreground": "#a1fb1a",
    "progressBar.background": "#a1fb1a",
    "quickInput.background": "#181818",
    "quickInput.foreground": "#d8d8d8",
    "quickInputTitle.background": "#171717",
    "quickInputList.focusBackground": "#262626",
    "scrollbarSlider.activeBackground": "#6a6a6a66",
    "scrollbarSlider.background": "#6a6a6a33",
    "scrollbarSlider.hoverBackground": "#6a6a6a55",
    "settings.checkboxBackground": "#181818",
    "settings.checkboxBorder": "#333333",
    "settings.dropdownBackground": "#181818",
    "settings.dropdownBorder": "#333333",
    "settings.focusedRowBackground": "#1f1f1f",
    "settings.focusedRowBorder": "#a1fb1a66",
    "settings.headerForeground": "#f0f0f0",
    "settings.modifiedItemIndicator": "#a1fb1a",
    "settings.numberInputBackground": "#181818",
    "settings.numberInputBorder": "#333333",
    "settings.rowHoverBackground": "#202020",
    "settings.textInputBackground": "#181818",
    "settings.textInputBorder": "#333333",
    "sideBar.background": "#111111",
    "sideBar.border": "#242424",
    "sideBar.foreground": "#cfcfcf",
    "sideBarSectionHeader.background": "#111111",
    "sideBarSectionHeader.border": "#242424",
    "sideBarTitle.foreground": "#d8d8d8",
    "sideBar.dropBackground": "#24242480",
    "statusBar.background": "#141414",
    "statusBar.border": "#303030",
    "statusBar.debuggingBackground": "#141414",
    "statusBar.debuggingBorder": "#303030",
    "statusBar.debuggingForeground": "#d8d8d8",
    "statusBar.foreground": "#d8d8d8",
    "statusBar.noFolderBackground": "#141414",
    "statusBar.noFolderBorder": "#303030",
    "statusBar.noFolderForeground": "#d8d8d8",
    "statusBarItem.activeBackground": "#303030",
    "statusBarItem.compactHoverBackground": "#242424",
    "statusBarItem.errorBackground": "#141414",
    "statusBarItem.errorForeground": "#db7672",
    "statusBarItem.focusBorder": "#a1fb1a",
    "statusBarItem.prominentBackground": "#202020",
    "statusBarItem.prominentForeground": "#d8d8d8",
    "statusBarItem.prominentHoverBackground": "#2a2a2a",
    "statusBarItem.remoteBackground": "#141414",
    "statusBarItem.remoteForeground": "#d8d8d8",
    "statusBarItem.warningBackground": "#141414",
    "statusBarItem.warningForeground": "#e0992d",
    "statusBarItem.hoverBackground": "#242424",
    "tab.activeBackground": "#171717",
    "tab.activeBorder": "#171717",
    "tab.activeModifiedBorder": "#a1fb1a",
    "tab.activeBorderTop": "#a1fb1a",
    "tab.activeForeground": "#eeeeee",
    "tab.border": "#242424",
    "tab.hoverBackground": "#202020",
    "tab.inactiveBackground": "#151515",
    "tab.inactiveForeground": "#777777",
    "tab.inactiveModifiedBorder": "#555555",
    "tab.lastPinnedBorder": "#303030",
    "tab.unfocusedActiveBackground": "#171717",
    "tab.unfocusedActiveForeground": "#bdbdbd",
    "tab.unfocusedInactiveBackground": "#151515",
    "tab.unfocusedInactiveForeground": "#666666",
    "terminal.background": "#171717",
    "terminal.border": "#303030",
    "terminal.dropBackground": "#24242480",
    "terminal.findMatchBackground": "#3b321f",
    "terminal.findMatchBorder": "#e0992d",
    "terminal.foreground": "#cfcfcf",
    "terminal.hoverHighlightBackground": "#242424",
    "terminal.inactiveSelectionBackground": "#27324480",
    "terminal.selectionBackground": "#273244",
    "terminal.tab.activeBorder": "#a1fb1a",
    "terminalCommandDecoration.defaultBackground": "#858585",
    "terminalCommandDecoration.errorBackground": "#db7672",
    "terminalCommandDecoration.successBackground": "#12b8a2",
    "terminalOverviewRuler.border": "#303030",
    "terminalStickyScroll.background": "#171717",
    "terminalStickyScroll.border": "#303030",
    "terminalStickyScrollHover.background": "#202020",
    "titleBar.activeBackground": "#171717",
    "titleBar.activeForeground": "#e8e8e8",
    "titleBar.border": "#303030",
    "titleBar.inactiveBackground": "#171717",
    "titleBar.inactiveForeground": "#777777",
    "window.activeBorder": "#303030",
    "window.inactiveBorder": "#242424",
    "toolbar.activeBackground": "#242424",
    "toolbar.hoverBackground": "#202020",
    "tree.indentGuidesStroke": "#2a2a2a",
    "walkThrough.embeddedEditorBackground": "#171717",
    "widget.border": "#2b2b2b",
    "widget.shadow": "#00000066",
};

Object.assign((theme as { colors: Record<string, string> }).colors, neutralWorkbenchColors);

writeJsonFile(targetThemePath, theme);
console.log(`Wrote ${targetThemePath}`);
